spring.application.name=Spring-Boot-Intro

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
springdoc.api-docs.version=openapi_3_0

jwt.expiration=3600000
jwt.secret=supasecretkey1reallysecret2extremelysecret3longenoughtiguess
